# Generated by Django 4.2 on 2023-04-13 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Elevator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("working", "WORKING"),
                            ("maintenance ", "MAINTENANCE"),
                        ],
                        default="working",
                        max_length=20,
                    ),
                ),
                ("currentFloor", models.IntegerField(default=0)),
                (
                    "doorState",
                    models.CharField(
                        choices=[("open", "OPEN"), ("close", "CLOSE")],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("idle", "IDLE"), ("moving ", "MOVING")],
                        default="idle",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ElevatorRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("sourceFloor", models.IntegerField()),
                ("destinationFloor", models.IntegerField()),
                (
                    "elevator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elevatorApp.elevator",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
