# Generated by Django 4.2 on 2023-04-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elevatorApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="elevatorrequest",
            name="status",
            field=models.CharField(
                choices=[("pending", "PENDING"), ("completed", "COMPLETED")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="elevator",
            name="state",
            field=models.CharField(
                choices=[("working", "WORKING"), ("maintenance", "MAINTENANCE")],
                default="working",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="elevator",
            name="status",
            field=models.CharField(
                choices=[
                    ("idle", "IDLE"),
                    ("movingup", "MOVINGUP"),
                    ("movingdown", "MOVINGDOWN"),
                ],
                default="idle",
                max_length=20,
            ),
        ),
    ]
