# Generated by Django 4.2 on 2023-04-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elevatorApp", "0002_elevatorrequest_status_alter_elevator_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elevatorrequest",
            name="destinationFloor",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="elevatorrequest",
            name="sourceFloor",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
